name: github-action-to-deploy-to-lambda

#on:
 
 #push:
  
  #branches: 
   #  - main*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    
    - name: Install depenedencies
    

