name: github-action-to-deploy-to-lambda

on:
 push: 
  branches: 
    - main*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.6.0 
    - name: Setup python
      uses: actions/setup-python@v4.4.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
         python-version: 3.8
    - name: Install libraries
      run: |
         cd function
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
    - name: Create zip
      run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
    - name: Upload zipped artifact
      uses: actions/upload-artifact@v3.1.1
      with:
         name: zipped-bundle
         path: ${{ github.sha }}.zip
  download:
    needs: build
    runs-on: ubuntu
    steps: 
    - name: Download artifact
      uses: actions/download-artifact@v3.0.1
      with:
         name: zipped-bundle
    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
       aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
       region: us-east-1
    - name: Copy to S3
      run: aws s3 cp ${{ github.sha }}.zip s3://test-bucket-1130912830/${{ github.sha }}.zip
    
      
      
    

